spring:
  jpa:
    database: h2
    open-in-view: false #
    show-sql: true   #sql 로그 볼지
    hibernate:
      ddl-auto: create  #JPA에서 테이블 새로 만들지 (개발에서만 create 사용/ 운영은 무조건 none)
    properties:
      hibernate:
        format_sql: true #로그 예쁘게 볼지
        # default_batch_fetch_size: 10
  datasource:
    url: jdbc:h2:mem:portfolio
    username: sa
    password:
    driver-class-name: org.h2.Driver #어떤 드라이버를 쓸 지
  h2:
    console: #h2콘솔 사용하고 경로 설정
      enabled: true
      path: /h2-console